### ISSUE TITLE
CodecCommander does work ONLY if darkwake=0 

### ISSUE THREAD

**Issue by hackaro** [RehabMan/EAPD-Codec-Commander#11]
hi there,

GA Z170X-Gaming5 with ALC1150 here ... CodecCommander v. 2.40 is effective is giving audio back after wakeup ONLY IF darkwake is set to 0. Otherwise if it's not set, it does NOT work. 

The last version - v. 2.51 - is totally ineffective no matter how the darkwake parameter is set. 

Let me know if you need any particular log.

**Comment by RehabMan** [comment]
I never find it necessary to use kernel flag darkwake.

**Comment by hackaro** [comment]
you answer is totally useless. You're supposed to help in finding a solution... 

v. 2.51 is NOT working anyway, even without dark wake set...

**Comment by RehabMan** [comment]
I cannot reproduce the problem you mention.  The source code is available.  You can add your own debugging in order to determine the problem.  There are also a few parameters you can tweak via ACPI or the Info.plist, so you should check into that.

If you find a bug or want to submit an enhancement, you can do so here.
